# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_ctcomputeR_wrappers", use_symbols = TRUE, package_name = "ctcomputeR")

#' @usage NULL
#' @useDynLib ctcomputeR, .registration = TRUE
NULL

#' Computes characteristics of a clinical trial with specified
#' power, sample size, etc.
#' @export
ctcompute <- function(n_patients, alpha, power, maybe_lower_spending_fcn, maybe_upper_spending_fcn, maybe_look_fractions, prop_treated, lambda_event_trt, lambda_event_ctrl, maybe_lambda_dropout, enrollment_rates, enrollment_times, maybe_custom_alpha_spend, r, tol) .Call(wrap__ctcompute, n_patients, alpha, power, maybe_lower_spending_fcn, maybe_upper_spending_fcn, maybe_look_fractions, prop_treated, lambda_event_trt, lambda_event_ctrl, maybe_lambda_dropout, enrollment_rates, enrollment_times, maybe_custom_alpha_spend, r, tol)

#' Computes range of sample sizes appropriate for given trial based on
#' heuristic of diminishing returns
#' @export
ss_range <- function(alpha, power, maybe_lower_spending_fcn, maybe_upper_spending_fcn, maybe_look_fractions, prop_treated, lambda_event_trt, lambda_event_ctrl, maybe_lambda_dropout, enrollment_rates, enrollment_times, maybe_custom_alpha_spend, tol, delta, min_perc_change) .Call(wrap__ss_range, alpha, power, maybe_lower_spending_fcn, maybe_upper_spending_fcn, maybe_look_fractions, prop_treated, lambda_event_trt, lambda_event_ctrl, maybe_lambda_dropout, enrollment_rates, enrollment_times, maybe_custom_alpha_spend, tol, delta, min_perc_change)


# nolint end
